version: '3.8'

services:
  api:
    build: .
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000 --reload
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 10s
      timeout: 1s
      start_period: 10s
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./app:/app/app
